name: Build and Release

on:
  push:
    tags:
      - "v*" # This workflow runs when a tag is pushed matching this pattern
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v1.9.0
        with:
          micromamba-version: "1.5.8-0"
          environment-file: environment.yml
          init-shell: powershell
          cache-environment: true
          post-cleanup: all

      - name: Upgrade Deppendencies
        run: micromamba run -n geo-env-master pip install --upgrade --no-deps --force-reinstall numpy pyinstaller

      - name: Package EXE Application
        run: micromamba run -n geo-env-master pyinstaller main.spec

      - name: Rename main.exe
        run: |
          mv dist/main.exe dist/App-${{ github.ref_name }}.exe

      - name: Create zip file
        run: Compress-Archive -Path dist\satband-*.exe, README.md, config.yaml, geometry.geojson -DestinationPath satband-${{ github.ref_name }}.zip

      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            satband-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
